#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRATE_DIR="${CASE_SEARCH_DIR:-"${ROOT_DIR}/case-search"}"
OUT_DIR="${CASE_SEARCH_OUT_DIR:-"${ROOT_DIR}/site/src/generated/case-search"}"
WASM_BINDGEN_BIN="${WASM_BINDGEN:-wasm-bindgen}"

# The CLI must match the wasm-bindgen crate version pinned in Cargo.lock.
WASM_BINDGEN_VERSION="$(sed -n '/^name = "wasm-bindgen"$/{n;s/^version = "\(.*\)"$/\1/p;}' "${CRATE_DIR}/Cargo.lock")"
if [[ -z "${WASM_BINDGEN_VERSION}" ]]; then
  echo "Could not find the wasm-bindgen version in ${CRATE_DIR}/Cargo.lock." >&2
  exit 1
fi

if ! command -v "${WASM_BINDGEN_BIN}" >/dev/null 2>&1; then
  cat >&2 <<MSG
wasm-bindgen CLI ${WASM_BINDGEN_VERSION} is required to build the case search engine.
Install it with:

  cargo install wasm-bindgen-cli --version ${WASM_BINDGEN_VERSION} --locked

MSG
  exit 127
fi

INSTALLED_VERSION="$("${WASM_BINDGEN_BIN}" --version | awk '{print $2}')"
if [[ "${INSTALLED_VERSION}" != "${WASM_BINDGEN_VERSION}" ]]; then
  echo "wasm-bindgen CLI ${WASM_BINDGEN_VERSION} is required; found ${INSTALLED_VERSION:-unknown} at ${WASM_BINDGEN_BIN}." >&2
  exit 1
fi

cargo build \
  --manifest-path "${CRATE_DIR}/Cargo.toml" \
  --release \
  --locked \
  --target wasm32-unknown-unknown

rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"
# The app passes the WebAssembly URL explicitly, so the glue needs no default path.
"${WASM_BINDGEN_BIN}" \
  --target web \
  --omit-default-module-path \
  --out-dir "${OUT_DIR}" \
  --out-name case_search \
  "${CRATE_DIR}/target/wasm32-unknown-unknown/release/case_search.wasm"

cat > "${OUT_DIR}/README.md" <<EOF
# Case Search Engine

Generated by \`scripts/build_case_search.sh\` from the \`case-search/\` crate (DataFusion compiled to WebAssembly, wasm-bindgen ${WASM_BINDGEN_VERSION}). Do not edit these files by hand.

Rebuild with \`npm --prefix site run build:case-search\`.
EOF

echo "Built case search engine at ${OUT_DIR}"
